
---
title: "Informaci칩n de N칩mina"
author: "Jose Londo침o"
output: pdf_document
---

```{r Preambulo,echo=F, message=F}
#install.packages("kableExtra")
library("knitr")
library("readxl")
library("kableExtra")

#Primero que todo hay que crear un data frame con info de las personas
db <- data.frame(c("Cedula","Celular"),c("C칩digo","Correo"), c("Salario", "Centro de costos"))
#Se quitan los nombres de las columnas del dataframe pues no interesan
colnames(db) <- NULL

#Se imprime la tabla y se formatea con ::kableExtra
kable(db) %>%
kable_styling(full_width = T) %>%
add_header_above(c("Nombre del reporte"=3))
```

\vspace{24pt}

```{r transacciones, echo=F, results="asis"}
options(xtable.comment = FALSE)
library("xtable")
transa<-read_xlsx("transacciones.xlsx", skip=2)
tripilis <- xtable(transa[1:5,c("Nro. Registro", "Tipo Asiento","Precio Neto/Subtotal", "Precio/Valor Bruto")])
align(tripilis) <- "|p{3cm}|p{3cm}|p{6cm}|p{3cm}|p{3cm}|"

print(tripilis, include.rownames=F)


```

```{r ssumatorias, echo=F, results="asis"}
library(xtable)
sumatorias <- data.frame("","",c("Sumatoria sumas",""), c("Sumatoria restas", "Saldo"))

sup<-xtable(sumatorias)
align(sup)<-"|p{3cm}|p{3cm}p{6cm}|p{3cm}|p{3cm}|"
print(sup, include.rownames=F, include.colnames=F, hline.after = c(0,1,2))



```





